spring:
  profiles:
    active: dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka,http://eureka8762.com:8762/eureka

---
spring:
  profiles: dev
  application:
    name: consumers
server:
  port: 8084
---
spring:
     profiles: test
     application:
       name: consumersTest
server:
  port: 8074